### ISSUE TITLE
请问模型在哪里下载

### ISSUE THREAD

**Issue by sunxirui310** [wuyuejinxia/prcv2019-mvb-renet#1]
windows环境
se_resnext50_32x4d-a260b3a4.pth和resnet50_ibn_a.pth.tar
请问这两个文件可否提供一下下载链接，谢谢。我担心在网上找的文件有差异。

**Comment by SyncdevWu** [comment]
http://data.lip6.fr/cadene/pretrainedmodels/se_resnext50_32x4d-a260b3a4.pth
https://drive.google.com/drive/folders/1thS2B8UOSBi_cJX6zRy6YYRwz_nVFI_S
