### ISSUE TITLE
MVB dataset

### ISSUE THREAD

**Issue by Jeet774505** [wuyuejinxia/prcv2019-mvb-renet#3]
Hello, I'm currently doing the work of baggage REID. I want to try MVB, but the registration channel seems to be closed, so would you please send me a data set? thank you very much indeed.my e-mail is 953225176@qq.com.

**Comment by fishhead2zju** [comment]
Did u get it?

**Comment by SyncdevWu** [comment]
链接: https://pan.baidu.com/s/1i_iO3JXgvVu93DQral6LQQ 提取码: afu2 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v5的分享
