### ISSUE TITLE
Dataset link seems dead

### ISSUE THREAD

**Issue by bmetge** [wuyuejinxia/prcv2019-mvb-renet#5]
Hi @SyncdevWu ,
Thanks a lot for this repo.
However it seems the download link if dead http://volumenet.cn/#/  :/
Do you by any chance still have this dataset and would you be willling sharing it ?

Thanks a lot.
Baptiste

**Comment by SyncdevWu** [comment]
链接: https://pan.baidu.com/s/134maD1Gro_bLVjlxhXbVHg 提取码: rz7t
在 2022年12月19日 +0800 23:06，Baptiste Metge ***@***.***>，写道：
